set(__QT_DEPLOY_TARGET_ipc_client_FILE C:/Dev/Wormhole/gui/build_windows/Debug/ipc_client.lib)
set(__QT_DEPLOY_TARGET_ipc_client_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_wormhole-gui_FILE C:/Dev/Wormhole/gui/build_windows/Debug/wormhole-gui.exe)
set(__QT_DEPLOY_TARGET_wormhole-gui_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_wormhole-gui_RUNTIME_DLLS C:/Qt/6.10.2/msvc2022_64/bin/Qt6Widgetsd.dll;C:/Qt/6.10.2/msvc2022_64/bin/Qt6Guid.dll;C:/Qt/6.10.2/msvc2022_64/bin/Qt6Cored.dll)
set(__QT_DEPLOY_TARGET_test_gui_ipc_FILE C:/Dev/Wormhole/gui/build_windows/Debug/test_gui_ipc.exe)
set(__QT_DEPLOY_TARGET_test_gui_ipc_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_test_gui_ipc_RUNTIME_DLLS C:/Qt/6.10.2/msvc2022_64/bin/Qt6Testd.dll;C:/Qt/6.10.2/msvc2022_64/bin/Qt6Cored.dll)
